language: python
dist: xenial
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
services:
  - xvfb
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=5.1
    - python: 2.7
      env: PLONE_VERSION=5.2
    - python: 3.6
      env: PLONE_VERSION=5.2
    - python: 3.7
      env: PLONE_VERSION=5.2
install:
  - sed -ie "s#plone-5.1.x.cfg#plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - virtualenv .
  - ./bin/pip install --upgrade pip
  - ./bin/pip install -r http://dist.plone.org/release/$PLONE_VERSION-latest/requirements.txt
  - ./bin/buildout -c travis.cfg annotate
  - ./bin/buildout -t 10 -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
after_failure:
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
  - firefox -v
