language: python
dist: xenial
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=5.1.x
    - python: 2.7
      env: PLONE_VERSION=5.2.x
    - python: 3.6
      env: PLONE_VERSION=5.2.x
    - python: 3.7
      env: PLONE_VERSION=5.2.x
install:
  - sed -ie "s#plone-5.1.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - pip install -U zc.buildout setuptools pip
  - buildout -c travis.cfg annotate
  - buildout -t 10 -Nc travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
after_failure:
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
  - firefox -v
